import { defineCollection, z } from "astro:content";
import { glob } from "astro/loaders";

const baseFields = {
  title: z.string(),
  description: z.string(),
  date: z.coerce.date(),
  updated: z.coerce.date().optional(),
  tags: z.array(z.string()).default([]),
  featured: z.boolean().default(false),
  draft: z.boolean().default(false),
};

const systemDesign = defineCollection({
  loader: glob({ pattern: "**/*.{md,mdx}", base: "./src/content/system-design" }),
  schema: z.object({
    ...baseFields,
    level: z.array(z.string()).optional(),
    companies: z.array(z.string()).optional(),
  }),
});

const coding = defineCollection({
  loader: glob({ pattern: "**/*.{md,mdx}", base: "./src/content/coding" }),
  schema: z.object({
    ...baseFields,
    difficulty: z.enum(["easy", "medium", "hard"]).optional(),
    patterns: z.array(z.string()).optional(),
    languages: z.array(z.string()).optional(),
    companies: z.array(z.string()).optional(),
  }),
});

const interviews = defineCollection({
  loader: glob({ pattern: "**/*.{md,mdx}", base: "./src/content/interviews" }),
  schema: z.object({
    ...baseFields,
    company: z.string().optional(),
    level: z.string().optional(),
    rounds: z.array(z.string()).optional(),
    sample: z.boolean().default(false),
  }),
});

// Generated by site/scripts/import-digests.mjs from ../digests/digest-*.md.
// Never hand-authored; the directory is gitignored.
const generatedDigests = defineCollection({
  loader: glob({ pattern: "**/*.{md,mdx}", base: "./src/content/generated-digests" }),
  schema: z.object({
    title: z.string(),
    date: z.coerce.date(),
    generated: z.boolean().default(true),
    articleCount: z.number().optional(),
    sourceCount: z.number().optional(),
    sources: z.array(z.string()).optional(),
  }),
});

export const collections = {
  "system-design": systemDesign,
  coding,
  interviews,
  "generated-digests": generatedDigests,
};
