import { defineCollection } from "astro:content";
import { glob } from "astro/loaders";
import { z } from "astro/zod";

const baseFields = {
  title: z.string(),
  description: z.string(),
  date: z.coerce.date(),
  updated: z.coerce.date().optional(),
  tags: z.array(z.string()).default([]),
  featured: z.boolean().default(false),
  draft: z.boolean().default(false),
  socialImage: z
    .object({
      src: z.string(),
      alt: z.string(),
      width: z.number().int().positive(),
      height: z.number().int().positive(),
    })
    .optional(),
  practice: z
    .array(
      z.object({
        question: z.string(),
        hint: z.string(),
        answer: z.string(),
        topic: z.string().optional(),
      })
    )
    .optional(),
};

const systemDesign = defineCollection({
  loader: glob({ pattern: "**/*.{md,mdx}", base: "./src/content/system-design" }),
  schema: z.object({
    ...baseFields,
    topic: z.string().optional(),
    level: z.array(z.string()).optional(),
    companies: z.array(z.string()).optional(),
  }),
});

const coding = defineCollection({
  loader: glob({ pattern: "**/*.{md,mdx}", base: "./src/content/coding" }),
  schema: z.object({
    ...baseFields,
    difficulty: z.enum(["easy", "medium", "hard"]).optional(),
    patterns: z.array(z.string()).optional(),
    languages: z.array(z.string()).optional(),
    companies: z.array(z.string()).optional(),
  }),
});

const interviews = defineCollection({
  loader: glob({ pattern: "**/*.{md,mdx}", base: "./src/content/interviews" }),
  schema: z.object({
    ...baseFields,
    company: z.string().optional(),
    level: z.string().optional(),
    rounds: z.array(z.string()).optional(),
    sample: z.boolean().default(false),
  }),
});

// Generated by site/scripts/import-digests.mjs from ../digests/digest-*.md.
// Never hand-authored; the directory is gitignored.
const generatedDigests = defineCollection({
  loader: glob({ pattern: "**/*.{md,mdx}", base: "./src/content/generated-digests" }),
  schema: z.object({
    title: z.string(),
    date: z.coerce.date(),
    generated: z.boolean().default(true),
    articleCount: z.number().optional(),
    sourceCount: z.number().optional(),
    sources: z.array(z.string()).optional(),
  }),
});

const generatedWeekly = defineCollection({
  loader: glob({ pattern: "**/*.{md,mdx}", base: "./src/content/generated-weekly" }),
  schema: z.object({
    title: z.string(),
    date: z.coerce.date(),
    weekStart: z.coerce.date(),
    weekEnd: z.coerce.date(),
    digestCount: z.number(),
    articleCount: z.number(),
    sourceCount: z.number(),
    complete: z.boolean(),
    topTopics: z.array(z.object({ name: z.string(), count: z.number() })),
    topSources: z.array(z.object({ name: z.string(), count: z.number() })),
    representativeArticles: z.array(
      z.object({
        title: z.string(),
        url: z.string(),
        source: z.string(),
        topic: z.string(),
        summary: z.string(),
      })
    ),
  }),
});

export const collections = {
  "system-design": systemDesign,
  coding,
  interviews,
  "generated-digests": generatedDigests,
  "generated-weekly": generatedWeekly,
};
